version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/song-api-db
    depends_on:
      - mongodb
    command: ['pm2-runtime', 'start', 'ecosystem.config.js']

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
