version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=${MONGO_URI} # This will be provided by Render's environment variables
    command: ['pm2-runtime', 'start', 'ecosystem.config.js']
